//
// TokensAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class TokensAPI: APIBase {
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accessTokensPost(body: Body? = nil, completion: @escaping ((_ data: Token?,_ error: Error?) -> Void)) {
        accessTokensPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**

     - parameter body: (body)  (optional)
     - returns: Observable<Token>
     */
    open class func accessTokensPost(body: Body? = nil) -> Observable<Token> {
        return Observable.create { observer -> Disposable in
            accessTokensPost(body: body) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     - POST /access_tokens
     - examples: [{example={
  "scopes" : [ "aeiou" ],
  "token" : "aeiou",
  "client_id" : "aeiou"
}, contentType=application/json}]
     
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Token> 
     */
    open class func accessTokensPostWithRequestBuilder(body: Body? = nil) -> RequestBuilder<Token> {
        let path = "/access_tokens"
        let URLString = CHQiitaApiClientAPI.basePath + path
        let parameters = body?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Token>.Type = CHQiitaApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
