//
// Token.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Token: JSONEncodable {

    public var clientId: String?
    public var scopes: [String]?
    public var token: String


    public init(clientId: String?=nil, scopes: [String]?=nil, token: String) {
        self.clientId = clientId
        self.scopes = scopes
        self.token = token
    }
    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["client_id"] = self.clientId
        nillableDictionary["scopes"] = self.scopes?.encodeToJSON()
        nillableDictionary["token"] = self.token

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
